backend:
  name: github
  repo: 416serg/gatsby-pro

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created At, widget: date }
      - { name: body, label: Post Content, widget: markdown }
      - { name: image, label: Image, widget: image }